required = ["github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger"]

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/infobloxopen/atlas-app-toolkit"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
